# Step 1. build_step
FROM golang:1.16-alpine3.13 AS builder
ARG APP=/app
RUN apk add make
# nickeskov: disable cgo for go build
ENV CGO_ENABLED=0
WORKDIR ${APP}
COPY go.mod .
RUN go mod download
COPY cmd cmd
COPY pkg pkg
COPY Makefile .
RUN make inside-docker-build

# Step 2. release_step
FROM alpine:3.13 AS main
ARG APP=/app
ENV TZ=Etc/UTC \
    APP_USER=calendar-bot
RUN addgroup -S $APP_USER \
    && adduser -S $APP_USER -G $APP_USER
USER $APP_USER
EXPOSE 2000
EXPOSE 8080
EXPOSE 8081
WORKDIR ${APP}
COPY --from=builder /app/build/bin/botbackend botbackend
CMD ["./botbackend"]
